export { VkIdButton } from './ui/vkIdButton'
export { AuthModal } from './ui/authModal'
export { initVkId, parseVkCallback } from './lib'
export { getCurrentUser, loginWithVk } from './api'
export type { VkAuthCallbackParams } from './lib'
